"""client_birth_date=string

Revision ID: 305defae1b41
Revises: e050ee570230
Create Date: 2024-08-29 00:18:44.197103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305defae1b41'
down_revision: Union[str, None] = 'e050ee570230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'birth_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'birth_date',
               existing_type=sa.String(length=30),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
